import os
from uuid import uuid4
from flask import Flask, request, render_template, send_from_directory
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.xception import preprocess_input


app = Flask(__name__)
# app = Flask(__name__, static_folder="images")



APP_ROOT = os.path.dirname(os.path.abspath(__file__))

species = ["AFRICAN CROWNED CRANE",
"AFRICAN FIREFINCH",
"ALBATROSS",
"ALEXANDRINE PARAKEET",
"AMERICAN AVOCET",
"AMERICAN BITTERN",
"AMERICAN COOT",
"AMERICAN GOLDFINCH",
"AMERICAN KESTREL",
"AMERICAN PIPIT",
"AMERICAN REDSTART",
"ANHINGA",
"ANNAS HUMMINGBIRD",
"ANTBIRD",
"ARARIPE MANAKIN",
"ASIAN CRESTED IBIS",
"BALD EAGLE",
"BALI STARLING",
"BALTIMORE ORIOLE",
"BANANAQUIT",
"BANDED BROADBILL",
"BAR-TAILED GODWIT",
"BARN OWL",
"BARN SWALLOW",
"BARRED PUFFBIRD",
"BAY-BREASTED WARBLER",
"BEARDED BARBET",
"BEARDED REEDLING",
"BELTED KINGFISHER",
"BIRD OF PARADISE",
"BLACK & YELLOW bROADBILL",
"BLACK FRANCOLIN",
"BLACK SKIMMER",
"BLACK SWAN",
"BLACK TAIL CRAKE",
"BLACK THROATED BUSHTIT",
"BLACK THROATED WARBLER",
"BLACK VULTURE",
"BLACK-CAPPED CHICKADEE",
"BLACK-NECKED GREBE",
"BLACK-THROATED SPARROW",
"BLACKBURNIAM WARBLER",
"BLUE GROUSE",
"BLUE HERON",
"BOBOLINK",
"BORNEAN BRISTLEHEAD",
"BORNEAN LEAFBIRD",
"BROWN NOODY",
"BROWN THRASHER",
"BULWERS PHEASANT",
"CACTUS WREN",
"CALIFORNIA CONDOR",
"CALIFORNIA GULL",
"CALIFORNIA QUAIL",
"CANARY",
"CAPE MAY WARBLER",
"CAPUCHINBIRD",
"CARMINE BEE-EATER",
"CASPIAN TERN",
"CASSOWARY",
"CEDAR WAXWING",
"CHARA DE COLLAR",
"CHIPPING SPARROW",
"CHUKAR PARTRIDGE",
"CINNAMON TEAL",
"COCK OF THE  ROCK",
"COCKATOO",
"COMMON FIRECREST",
"COMMON GRACKLE",
"COMMON HOUSE MARTIN",
"COMMON LOON",
"COMMON POORWILL",
"COMMON STARLING",
"COUCHS KINGBIRD",
"CRESTED AUKLET",
"CRESTED CARACARA",
"CRESTED NUTHATCH",
"CROW",
"CROWNED PIGEON",
"CUBAN TODY",
"CURL CRESTED ARACURI",
"D-ARNAUDS BARBET",
"DARK EYED JUNCO",
"DOUBLE BARRED FINCH",
"DOWNY WOODPECKER",
"EASTERN BLUEBIRD",
"EASTERN MEADOWLARK",
"EASTERN ROSELLA",
"EASTERN TOWEE",
"ELEGANT TROGON",
"ELLIOTS  PHEASANT",
"EMPEROR PENGUIN",
"EMU",
"ENGGANO MYNA",
"EURASIAN GOLDEN ORIOLE",
"EURASIAN MAGPIE",
"EVENING GROSBEAK",
"FIRE TAILLED MYZORNIS",
"FLAME TANAGER",
"FLAMINGO",
"FRIGATE",
"GAMBELS QUAIL",
"GANG GANG COCKATOO",
"GILA WOODPECKER",
"GILDED FLICKER",
"GLOSSY IBIS",
"GO AWAY BIRD",
"GOLD WING WARBLER",
"GOLDEN CHEEKED WARBLER",
"GOLDEN CHLOROPHONIA",
"GOLDEN EAGLE",
"GOLDEN PHEASANT",
"GOLDEN PIPIT",
"GOULDIAN FINCH",
"GRAY CATBIRD",
"GRAY PARTRIDGE",
"GREAT POTOO",
"GREATOR SAGE GROUSE",
"GREEN JAY",
"GREEN MAGPIE",
"GREY PLOVER",
"GUINEA TURACO",
"GUINEAFOWL",
"GYRFALCON",
"HARPY EAGLE",
"HAWAIIAN GOOSE",
"HELMET VANGA",
"HIMALAYAN MONAL",
"HOATZIN",
"HOODED MERGANSER",
"HOOPOES",
"HORNBILL",
"HORNED GUAN",
"HORNED SUNGEM",
"HOUSE FINCH",
"HOUSE SPARROW",
"IMPERIAL SHAQ",
"INCA TERN",
"INDIAN BUSTARD",
"INDIAN PITTA",
"INDIGO BUNTING",
"JABIRU",
"JAVA SPARROW",
"KAKAPO",
"KILLDEAR",
"KING VULTURE",
"KIWI",
"KOOKABURRA",
"LARK BUNTING",
"LEARS MACAW",
"LILAC ROLLER",
"LONG-EARED OWL",
"MAGPIE GOOSE",
"MALABAR HORNBILL",
"MALACHITE KINGFISHER",
"MALEO",
"MALLARD DUCK",
"MANDRIN DUCK",
"MARABOU STORK",
"MASKED BOOBY",
"MASKED LAPWING",
"MIKADO  PHEASANT",
"MOURNING DOVE",
"MYNA",
"NICOBAR PIGEON",
"NOISY FRIARBIRD",
"NORTHERN BALD IBIS",
"NORTHERN CARDINAL",
"NORTHERN FLICKER",
"NORTHERN GANNET",
"NORTHERN GOSHAWK",
"NORTHERN JACANA",
"NORTHERN MOCKINGBIRD",
"NORTHERN PARULA",
"NORTHERN RED BISHOP",
"NORTHERN SHOVELER",
"OCELLATED TURKEY",
"OKINAWA RAIL",
"OSPREY",
"OSTRICH",
"OYSTER CATCHER",
"PAINTED BUNTIG",
"PALILA",
"PARADISE TANAGER",
"PARUS MAJOR",
"PEACOCK",
"PELICAN",
"PEREGRINE FALCON",
"PHILIPPINE EAGLE",
"PINK ROBIN",
"PUFFIN",
"PURPLE FINCH",
"PURPLE GALLINULE",
"PURPLE MARTIN",
"PURPLE SWAMPHEN",
"QUETZAL",
"RAINBOW LORIKEET",
"RAZORBILL",
"RED BEARDED BEE EATER",
"RED BELLIED PITTA",
"RED BROWED FINCH",
"RED FACED CORMORANT",
"RED FACED WARBLER",
"RED HEADED DUCK",
"RED HEADED WOODPECKER",
"RED HONEY CREEPER",
"RED TAILED THRUSH",
"RED WINGED BLACKBIRD",
"RED WISKERED BULBUL",
"REGENT BOWERBIRD",
"RING-NECKED PHEASANT",
"ROADRUNNER",
"ROBIN",
"ROCK DOVE",
"ROSY FACED LOVEBIRD",
"ROUGH LEG BUZZARD",
"ROYAL FLYCATCHER",
"RUBY THROATED HUMMINGBIRD",
"RUFOUS KINGFISHER",
"RUFUOS MOTMOT",
"SAMATRAN THRUSH",
"SAND MARTIN",
"SCARLET IBIS",
"SCARLET MACAW",
"SHOEBILL",
"SHORT BILLED DOWITCHER",
"SMITHS LONGSPUR",
"SNOWY EGRET",
"SNOWY OWL",
"SORA",
"SPANGLED COTINGA",
"SPLENDID WREN",
"SPOON BILED SANDPIPER",
"SPOONBILL",
"SRI LANKA BLUE MAGPIE",
"STEAMER DUCK",
"STORK BILLED KINGFISHER",
"STRAWBERRY FINCH",
"STRIPPED SWALLOW",
"SUPERB STARLING",
"SWINHOES PHEASANT",
"TAIWAN MAGPIE",
"TAKAHE",
"TASMANIAN HEN",
"TEAL DUCK",
"TIT MOUSE",
"TOUCHAN",
"TOWNSENDS WARBLER",
"TREE SWALLOW",
"TRUMPTER SWAN",
"TURKEY VULTURE",
"TURQUOISE MOTMOT",
"UMBRELLA BIRD",
"VARIED THRUSH",
"VENEZUELIAN TROUPIAL",
"VERMILION FLYCATHER",
"VICTORIA CROWNED PIGEON",
"VIOLET GREEN SWALLOW",
"VULTURINE GUINEAFOWL",
"WATTLED CURASSOW",
"WHIMBREL",
"WHITE CHEEKED TURACO",
"WHITE NECKED RAVEN",
"WHITE TAILED TROPIC",
"WILD TURKEY",
"WILSONS BIRD OF PARADISE",
"WOOD DUCK",
"YELLOW BELLIED FLOWERPECKER",
"YELLOW CACIQUE",
"YELLOW HEADED BLACKBIRD"]

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/upload", methods=["POST"])
def upload():
    target = os.path.join(APP_ROOT, 'images/')
    #target = os.path.join(APP_ROOT, 'static/')
    print(target)
    if not os.path.isdir(target):
        os.mkdir(target)
    else:
        print("Couldn't create upload directory: {}".format(target))
    print(request.files.getlist("file"))
    for upload in request.files.getlist("file"):
        print(upload)
        print("{} is the file name".format(upload.filename))
        filename = upload.filename
        destination = '/'.join([target, filename])
        print("Accept incoming file:", filename)
        print("Save it to:", destination)
        upload.save(destination)


        #Predicting image 
        model = load_model(
            'weights_xception.h5', compile=True)

        img = image.load_img('images\\'+filename, target_size=(224, 224))
        img = np.array(img)
        img = np.expand_dims(img, axis=0)
        img = preprocess_input(img)                                      

        pred = model.predict(img)

        index = np.argmax(pred)

        prediction = species[index]
        print(prediction)


    # return send_from_directory("images", filename, as_attachment=True)
    return render_template("template.html", image_name=filename, text=prediction)

@app.route('/upload/<filename>')
def send_image(filename):
    return send_from_directory("images", filename)

if __name__ == "__main__":
    app.run(debug=False)
